### PR TITLE
Make the pp3 profiles partial

### PR DESCRIPTION
**Pull request by sguyader**
@patdavid I don't know how to do this, but I 'd like to my changes to be reflected on https://github.com/pixlsus/RawTherapee-Presets
Can you help?

### CODE REVIEW

**Comment by patdavid** [comment]
Sure!  Checking now, give me a moment...

**Comment by patdavid** [comment]
Ah!  Ok, Let me create a patch from this and apply the diff to the files in that other repo.

If you want to keep working on those other files, probably best to clone that other repo, https://github.com/pixlsus/RawTherapee-Presets.

I'll check and add you as a dev on the org just in case you're not already.  Then you'll be able to push directly to the repo yourself if you want.

**Comment by patdavid** [comment]
@sguyader - I've applied your changes as a patch to the https://github.com/pixlsus/RawTherapee-Presets repository.  Your changes should now be reflected in those files!

https://github.com/pixlsus/RawTherapee-Presets/commit/cef09ef49e8484de3aa65439b0f95b07e032e34a

**Comment by sguyader** [comment]
Thanks Pat. I cloned the other repo at first, but it didn't allow me to
commit.

**Comment by patdavid** [comment]
@sguyader Ok, I've fixed that and you should now have write permissions to pixlsus/RawTherapee-Presets (you may have to re-clone the repo).  Happy Hacking! :D

**Pull request merged**
